#!/usr/bin/env bash
# Excludes developer tool build artifacts, caches, and emulator images from
# iCloud Drive, Spotlight indexing, and Time Machine backups.
#
# Run after any SDK update, clean build, or first emulator creation.
# Safe to re-run; silently skips missing directories.
#
# What each mechanism does:
#   iCloud (com.apple.icloud.donotbackup xattr)
#     Prevents iCloud Drive from uploading the directory.
#     Only meaningful for paths inside ~/Documents or ~/Desktop.
#
#   Spotlight (.metadata_never_index file)
#     Prevents mds_stores/mdworker from indexing the directory.
#     Applies to ANY path — the main fix for mds_stores CPU spikes
#     after SDK updates or new emulator images.
#
#   Time Machine (tmutil addexclusion, no sudo required)
#     Prevents Time Machine from backing up the directory.
#     Applies to any path.

set -euo pipefail

BOLD=$'\033[1m'; RESET=$'\033[0m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; DIM=$'\033[2m'
ok()   { echo "  ${GREEN}✓${RESET}  $1"; }
skip() { echo "  ${DIM}–${RESET}  $1 ${DIM}(not found)${RESET}"; }
warn() { echo "  ${YELLOW}!${RESET}  $1"; }

# ---------------------------------------------------------------------------
# Core helpers
# ---------------------------------------------------------------------------

apply_icloud() {
  local dir="$1"
  [ -d "$dir" ] || return 0
  xattr -w com.apple.icloud.donotbackup 1 "$dir" 2>/dev/null \
    && ok "iCloud  excluded: $dir" \
    || warn "iCloud  FAILED:   $dir"
}

apply_spotlight() {
  local dir="$1"
  [ -d "$dir" ] || return 0
  touch "$dir/.metadata_never_index" 2>/dev/null \
    && ok "Spotlight excluded: $dir" \
    || warn "Spotlight FAILED:  $dir"
}

apply_timemachine() {
  local dir="$1"
  [ -d "$dir" ] || return 0
  tmutil addexclusion "$dir" 2>/dev/null \
    && ok "TimeMachine excluded: $dir" \
    || warn "TimeMachine FAILED:  $dir"
}

# All three at once (for paths inside iCloud Drive scope, e.g. ~/Documents)
apply_all_icloud() {
  local dir="$1"
  if [ ! -d "$dir" ]; then skip "$dir"; return 0; fi
  apply_icloud       "$dir"
  apply_spotlight    "$dir"
  apply_timemachine  "$dir"
}

# Spotlight + Time Machine only (for paths outside iCloud Drive scope)
apply_all_library() {
  local dir="$1"
  if [ ! -d "$dir" ]; then skip "$dir"; return 0; fi
  apply_spotlight    "$dir"
  apply_timemachine  "$dir"
}

# ---------------------------------------------------------------------------
# 1. Project source — inside ~/Documents (iCloud Drive scope)
# ---------------------------------------------------------------------------
echo ""
echo "${BOLD}── Project source (~/Documents/src) ──────────────────────────────${RESET}"

PROJECT="${HOME}/Documents/src/bubble/TJ-branch-20260220"

# node_modules (root + mobile)
apply_all_icloud "${PROJECT}/node_modules"
apply_all_icloud "${PROJECT}/mobile/node_modules"

# Android build artifacts
apply_all_icloud "${PROJECT}/mobile/android/build"
apply_all_icloud "${PROJECT}/mobile/android/.gradle"
apply_all_icloud "${PROJECT}/mobile/android/app/build"
apply_all_icloud "${PROJECT}/mobile/android/app/.cxx"

# iOS native project (generated by expo prebuild — rebuilt on demand)
apply_all_icloud "${PROJECT}/mobile/ios"

# General build outputs
apply_all_icloud "${PROJECT}/dist"
apply_all_icloud "${PROJECT}/.expo"

# ---------------------------------------------------------------------------
# 2. Android SDK & AVDs — ~/Library/Android, ~/.android
#    These are NOT in iCloud scope but Spotlight indexes them aggressively
#    after SDK updates (23 GB system-images, 29 GB AVD disk images).
# ---------------------------------------------------------------------------
echo ""
echo "${BOLD}── Android SDK & AVDs ────────────────────────────────────────────${RESET}"

apply_all_library "${HOME}/Library/Android/sdk/system-images"
apply_all_library "${HOME}/Library/Android/sdk/emulator"
apply_all_library "${HOME}/Library/Android/sdk/build-tools"
apply_all_library "${HOME}/Library/Android/sdk/platforms"
apply_all_library "${HOME}/Library/Android/sdk/ndk"
apply_all_library "${HOME}/Library/Android/sdk/cmake"
apply_all_library "${HOME}/.android/avd"
apply_all_library "${HOME}/.gradle/caches"
apply_all_library "${HOME}/.gradle/wrapper"

# ---------------------------------------------------------------------------
# 3. Xcode & iOS Simulator — ~/Library/Developer
#    DerivedData and CoreSimulator devices are rebuilt/re-downloaded on demand.
# ---------------------------------------------------------------------------
echo ""
echo "${BOLD}── Xcode & iOS Simulator ─────────────────────────────────────────${RESET}"

apply_all_library "${HOME}/Library/Developer/Xcode/DerivedData"
apply_all_library "${HOME}/Library/Developer/Xcode/iOS DeviceSupport"
apply_all_library "${HOME}/Library/Developer/CoreSimulator/Devices"
apply_all_library "${HOME}/Library/Developer/CoreSimulator/Caches"
apply_all_library "${HOME}/Library/Developer/CoreSimulator/Temp"
apply_all_library "${HOME}/Library/Caches/com.apple.dt.Xcode"
apply_all_library "${HOME}/Library/Caches/com.apple.dt.instruments"

# ---------------------------------------------------------------------------
# 4. Genymotion — auto-detect VM storage path
#    Genymotion 3.x uses its own hypervisor; VMs live in Application Support.
#    Check the preferences plist for a custom path first.
# ---------------------------------------------------------------------------
echo ""
echo "${BOLD}── Genymotion ────────────────────────────────────────────────────${RESET}"

# Read custom VM storage path from Genymotion preferences if set
GENY_VM_PATH=$(defaults read com.genymobile.Genymotion vmStoragePath 2>/dev/null || true)

if [ -z "$GENY_VM_PATH" ]; then
  # Genymotion 3.x default locations (try both)
  GENY_VM_PATH="${HOME}/Library/Application Support/Genymobile/Genymotion/deployed"
fi

apply_all_library "${GENY_VM_PATH}"

# Also exclude the Genymotion app support dirs regardless
apply_all_library "${HOME}/Library/Application Support/Genymobile"
apply_all_library "${HOME}/Library/Application Support/Genymotion"
apply_all_library "${HOME}/Library/Caches/Genymobile"

# ---------------------------------------------------------------------------
# 5. Note for directories that require re-running
# ---------------------------------------------------------------------------
echo ""
echo "${BOLD}── Notes ─────────────────────────────────────────────────────────${RESET}"
echo "  Re-run this script after:"
echo "  • expo prebuild / expo run:android  (recreates mobile/android/ tree)"
echo "  • ./gradlew clean                   (recreates android build dirs)"
echo "  • Android Studio SDK updates        (new system-images or build-tools)"
echo "  • Creating a new Genymotion VM      (new VM directory in deployed/)"
echo ""
echo "  Spotlight won't re-index excluded dirs until the .metadata_never_index"
echo "  file is removed. You can verify with: mdutil -s <path>"
echo ""
