-- meta schema: operational metadata that must SURVIVE app-data resets.
-- Resets drop only the `public` schema, so anything here persists across reseeds.
-- All statements are idempotent (IF NOT EXISTS) — safe to run repeatedly.

CREATE SCHEMA IF NOT EXISTS meta;

-- Append-only journal of observations/requirements about this database & server.
-- Used by the qa runner's production-guard (classify = latest env:* entry wins) and by
-- anyone debugging "what is in this DB and is it safe to wipe?". Entries are lightly
-- human-readable; later entries may contradict/overturn earlier ones.
CREATE TABLE IF NOT EXISTS meta.testing_journal (
    entry_id    BIGSERIAL PRIMARY KEY,
    entry_time  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    observation TEXT NOT NULL CHECK (char_length(observation) <= 500),
    author      VARCHAR(100),
    tags        TEXT[]
);

CREATE INDEX IF NOT EXISTS idx_journal_entry_time ON meta.testing_journal (entry_time DESC);
CREATE INDEX IF NOT EXISTS idx_journal_tags       ON meta.testing_journal USING GIN (tags);

-- Schema baseline: a per-table fingerprint of the column layout captured at provision time
-- (when the DB is known to match shared/schema.ts). The runner's schema-drift gate compares the
-- live schema to this baseline; `column_def` is kept verbatim so drift can name the exact
-- column that was added/removed (e.g. users.suspended_at), not just "this table changed".
-- Lives in `meta` so it survives public-schema resets. Replaced wholesale on each provision.
CREATE TABLE IF NOT EXISTS meta.schema_baseline (
    table_name  TEXT PRIMARY KEY,
    column_def  TEXT NOT NULL,            -- sorted "col:type:nullable:default" lines for the table
    rollup      TEXT NOT NULL,            -- whole-DB schema rollup at capture time (same for all rows)
    captured_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    label       TEXT
);

-- Optional reference vocabularies (informational; not FK-enforced on the journal so that
-- ad-hoc tags remain possible). Populated lazily; safe to leave empty.
CREATE TABLE IF NOT EXISTS meta.observation_types (
    type_key    VARCHAR(50) PRIMARY KEY,
    description TEXT
);

CREATE TABLE IF NOT EXISTS meta.standard_tags (
    tag         VARCHAR(80) PRIMARY KEY,
    description TEXT
);

-- Seed the standard environment tags the guard understands (idempotent).
INSERT INTO meta.standard_tags (tag, description) VALUES
    ('env:test',            'Dedicated, disposable test database. Destructive ops allowed.'),
    ('env:local',           'Local developer database used for testing. Destructive ops allowed.'),
    ('env:ci',              'CI test database. Destructive ops allowed.'),
    ('env:staging',         'Staging database. Treated as production for destructive ops.'),
    ('env:production',      'Production database. Destructive ops always blocked.'),
    ('env:production-like', 'Holds a copy of production data. Destructive ops blocked.'),
    ('data-class:synthetic',       'Data was generated by the seeder.'),
    ('data-class:production-copy',  'Data was imported/restored from production.'),
    ('destructive-ok',      'Operator marker: destructive testing is permitted here.'),
    ('destructive-not-ok',  'Operator marker: do not run destructive operations here.')
ON CONFLICT (tag) DO NOTHING;
